# -*- coding: utf-8 -*-
# :Project:   pglast -- DO NOT EDIT: automatically extracted from parsenodes.h @ 10-1.0.2-0-gd710cb0
# :Author:    Lele Gaifax <lele@metapensiero.it>
# :License:   GNU General Public License version 3 or later
# :Copyright: © 2017-2019 Lele Gaifax
#

from __future__ import absolute_import, division, print_function, unicode_literals
from enum import IntEnum, Enum


class A_Expr_Kind(IntEnum):
    AEXPR_OP = 0
    AEXPR_OP_ANY = 1
    AEXPR_OP_ALL = 2
    AEXPR_DISTINCT = 3
    AEXPR_NOT_DISTINCT = 4
    AEXPR_NULLIF = 5
    AEXPR_OF = 6
    AEXPR_IN = 7
    AEXPR_LIKE = 8
    AEXPR_ILIKE = 9
    AEXPR_SIMILAR = 10
    AEXPR_BETWEEN = 11
    AEXPR_NOT_BETWEEN = 12
    AEXPR_BETWEEN_SYM = 13
    AEXPR_NOT_BETWEEN_SYM = 14
    AEXPR_PAREN = 15

class AlterSubscriptionType(IntEnum):
    ALTER_SUBSCRIPTION_OPTIONS = 0
    ALTER_SUBSCRIPTION_CONNECTION = 1
    ALTER_SUBSCRIPTION_PUBLICATION = 2
    ALTER_SUBSCRIPTION_REFRESH = 3
    ALTER_SUBSCRIPTION_ENABLED = 4

class AlterTSConfigType(IntEnum):
    ALTER_TSCONFIG_ADD_MAPPING = 0
    ALTER_TSCONFIG_ALTER_MAPPING_FOR_TOKEN = 1
    ALTER_TSCONFIG_REPLACE_DICT = 2
    ALTER_TSCONFIG_REPLACE_DICT_FOR_TOKEN = 3
    ALTER_TSCONFIG_DROP_MAPPING = 4

class AlterTableType(IntEnum):
    AT_AddColumn = 0
    AT_AddColumnRecurse = 1
    AT_AddColumnToView = 2
    AT_ColumnDefault = 3
    AT_DropNotNull = 4
    AT_SetNotNull = 5
    AT_SetStatistics = 6
    AT_SetOptions = 7
    AT_ResetOptions = 8
    AT_SetStorage = 9
    AT_DropColumn = 10
    AT_DropColumnRecurse = 11
    AT_AddIndex = 12
    AT_ReAddIndex = 13
    AT_AddConstraint = 14
    AT_AddConstraintRecurse = 15
    AT_ReAddConstraint = 16
    AT_AlterConstraint = 17
    AT_ValidateConstraint = 18
    AT_ValidateConstraintRecurse = 19
    AT_ProcessedConstraint = 20
    AT_AddIndexConstraint = 21
    AT_DropConstraint = 22
    AT_DropConstraintRecurse = 23
    AT_ReAddComment = 24
    AT_AlterColumnType = 25
    AT_AlterColumnGenericOptions = 26
    AT_ChangeOwner = 27
    AT_ClusterOn = 28
    AT_DropCluster = 29
    AT_SetLogged = 30
    AT_SetUnLogged = 31
    AT_AddOids = 32
    AT_AddOidsRecurse = 33
    AT_DropOids = 34
    AT_SetTableSpace = 35
    AT_SetRelOptions = 36
    AT_ResetRelOptions = 37
    AT_ReplaceRelOptions = 38
    AT_EnableTrig = 39
    AT_EnableAlwaysTrig = 40
    AT_EnableReplicaTrig = 41
    AT_DisableTrig = 42
    AT_EnableTrigAll = 43
    AT_DisableTrigAll = 44
    AT_EnableTrigUser = 45
    AT_DisableTrigUser = 46
    AT_EnableRule = 47
    AT_EnableAlwaysRule = 48
    AT_EnableReplicaRule = 49
    AT_DisableRule = 50
    AT_AddInherit = 51
    AT_DropInherit = 52
    AT_AddOf = 53
    AT_DropOf = 54
    AT_ReplicaIdentity = 55
    AT_EnableRowSecurity = 56
    AT_DisableRowSecurity = 57
    AT_ForceRowSecurity = 58
    AT_NoForceRowSecurity = 59
    AT_GenericOptions = 60
    AT_AttachPartition = 61
    AT_DetachPartition = 62
    AT_AddIdentity = 63
    AT_SetIdentity = 64
    AT_DropIdentity = 65

class ConstrType(IntEnum):
    CONSTR_NULL = 0
    CONSTR_NOTNULL = 1
    CONSTR_DEFAULT = 2
    CONSTR_IDENTITY = 3
    CONSTR_CHECK = 4
    CONSTR_PRIMARY = 5
    CONSTR_UNIQUE = 6
    CONSTR_EXCLUSION = 7
    CONSTR_FOREIGN = 8
    CONSTR_ATTR_DEFERRABLE = 9
    CONSTR_ATTR_NOT_DEFERRABLE = 10
    CONSTR_ATTR_DEFERRED = 11
    CONSTR_ATTR_IMMEDIATE = 12

class DefElemAction(IntEnum):
    DEFELEM_UNSPEC = 0
    DEFELEM_SET = 1
    DEFELEM_ADD = 2
    DEFELEM_DROP = 3

class DiscardMode(IntEnum):
    DISCARD_ALL = 0
    DISCARD_PLANS = 1
    DISCARD_SEQUENCES = 2
    DISCARD_TEMP = 3

class DropBehavior(IntEnum):
    DROP_RESTRICT = 0
    DROP_CASCADE = 1

class FetchDirection(IntEnum):
    FETCH_FORWARD = 0
    FETCH_BACKWARD = 1
    FETCH_ABSOLUTE = 2
    FETCH_RELATIVE = 3

class FunctionParameterMode(str, Enum):
    FUNC_PARAM_IN = 'i'
    FUNC_PARAM_OUT = 'o'
    FUNC_PARAM_INOUT = 'b'
    FUNC_PARAM_VARIADIC = 'v'
    FUNC_PARAM_TABLE = 't'

class GrantObjectType(IntEnum):
    ACL_OBJECT_COLUMN = 0
    ACL_OBJECT_RELATION = 1
    ACL_OBJECT_SEQUENCE = 2
    ACL_OBJECT_DATABASE = 3
    ACL_OBJECT_DOMAIN = 4
    ACL_OBJECT_FDW = 5
    ACL_OBJECT_FOREIGN_SERVER = 6
    ACL_OBJECT_FUNCTION = 7
    ACL_OBJECT_LANGUAGE = 8
    ACL_OBJECT_LARGEOBJECT = 9
    ACL_OBJECT_NAMESPACE = 10
    ACL_OBJECT_TABLESPACE = 11
    ACL_OBJECT_TYPE = 12

class GrantTargetType(IntEnum):
    ACL_TARGET_OBJECT = 0
    ACL_TARGET_ALL_IN_SCHEMA = 1
    ACL_TARGET_DEFAULTS = 2

class GroupingSetKind(IntEnum):
    GROUPING_SET_EMPTY = 0
    GROUPING_SET_SIMPLE = 1
    GROUPING_SET_ROLLUP = 2
    GROUPING_SET_CUBE = 3
    GROUPING_SET_SETS = 4

class ImportForeignSchemaType(IntEnum):
    FDW_IMPORT_SCHEMA_ALL = 0
    FDW_IMPORT_SCHEMA_LIMIT_TO = 1
    FDW_IMPORT_SCHEMA_EXCEPT = 2

class ObjectType(IntEnum):
    OBJECT_ACCESS_METHOD = 0
    OBJECT_AGGREGATE = 1
    OBJECT_AMOP = 2
    OBJECT_AMPROC = 3
    OBJECT_ATTRIBUTE = 4
    OBJECT_CAST = 5
    OBJECT_COLUMN = 6
    OBJECT_COLLATION = 7
    OBJECT_CONVERSION = 8
    OBJECT_DATABASE = 9
    OBJECT_DEFAULT = 10
    OBJECT_DEFACL = 11
    OBJECT_DOMAIN = 12
    OBJECT_DOMCONSTRAINT = 13
    OBJECT_EVENT_TRIGGER = 14
    OBJECT_EXTENSION = 15
    OBJECT_FDW = 16
    OBJECT_FOREIGN_SERVER = 17
    OBJECT_FOREIGN_TABLE = 18
    OBJECT_FUNCTION = 19
    OBJECT_INDEX = 20
    OBJECT_LANGUAGE = 21
    OBJECT_LARGEOBJECT = 22
    OBJECT_MATVIEW = 23
    OBJECT_OPCLASS = 24
    OBJECT_OPERATOR = 25
    OBJECT_OPFAMILY = 26
    OBJECT_POLICY = 27
    OBJECT_PUBLICATION = 28
    OBJECT_PUBLICATION_REL = 29
    OBJECT_ROLE = 30
    OBJECT_RULE = 31
    OBJECT_SCHEMA = 32
    OBJECT_SEQUENCE = 33
    OBJECT_SUBSCRIPTION = 34
    OBJECT_STATISTIC_EXT = 35
    OBJECT_TABCONSTRAINT = 36
    OBJECT_TABLE = 37
    OBJECT_TABLESPACE = 38
    OBJECT_TRANSFORM = 39
    OBJECT_TRIGGER = 40
    OBJECT_TSCONFIGURATION = 41
    OBJECT_TSDICTIONARY = 42
    OBJECT_TSPARSER = 43
    OBJECT_TSTEMPLATE = 44
    OBJECT_TYPE = 45
    OBJECT_USER_MAPPING = 46
    OBJECT_VIEW = 47

class OverridingKind(IntEnum):
    OVERRIDING_NOT_SET = 0
    OVERRIDING_USER_VALUE = 1
    OVERRIDING_SYSTEM_VALUE = 2

class PartitionRangeDatumKind(IntEnum):
    PARTITION_RANGE_DATUM_MINVALUE = -1
    PARTITION_RANGE_DATUM_VALUE = 0
    PARTITION_RANGE_DATUM_MAXVALUE = 1

class QuerySource(IntEnum):
    QSRC_ORIGINAL = 0
    QSRC_PARSER = 1
    QSRC_INSTEAD_RULE = 2
    QSRC_QUAL_INSTEAD_RULE = 3
    QSRC_NON_INSTEAD_RULE = 4

class RTEKind(IntEnum):
    RTE_RELATION = 0
    RTE_SUBQUERY = 1
    RTE_JOIN = 2
    RTE_FUNCTION = 3
    RTE_TABLEFUNC = 4
    RTE_VALUES = 5
    RTE_CTE = 6
    RTE_NAMEDTUPLESTORE = 7

class ReindexObjectType(IntEnum):
    REINDEX_OBJECT_INDEX = 0
    REINDEX_OBJECT_TABLE = 1
    REINDEX_OBJECT_SCHEMA = 2
    REINDEX_OBJECT_SYSTEM = 3
    REINDEX_OBJECT_DATABASE = 4

class RoleSpecType(IntEnum):
    ROLESPEC_CSTRING = 0
    ROLESPEC_CURRENT_USER = 1
    ROLESPEC_SESSION_USER = 2
    ROLESPEC_PUBLIC = 3

class RoleStmtType(IntEnum):
    ROLESTMT_ROLE = 0
    ROLESTMT_USER = 1
    ROLESTMT_GROUP = 2

class SetOperation(IntEnum):
    SETOP_NONE = 0
    SETOP_UNION = 1
    SETOP_INTERSECT = 2
    SETOP_EXCEPT = 3

class SortByDir(IntEnum):
    SORTBY_DEFAULT = 0
    SORTBY_ASC = 1
    SORTBY_DESC = 2
    SORTBY_USING = 3

class SortByNulls(IntEnum):
    SORTBY_NULLS_DEFAULT = 0
    SORTBY_NULLS_FIRST = 1
    SORTBY_NULLS_LAST = 2

class TableLikeOption(IntEnum):
    CREATE_TABLE_LIKE_DEFAULTS = 1 << 0
    CREATE_TABLE_LIKE_CONSTRAINTS = 1 << 1
    CREATE_TABLE_LIKE_IDENTITY = 1 << 2
    CREATE_TABLE_LIKE_INDEXES = 1 << 3
    CREATE_TABLE_LIKE_STORAGE = 1 << 4
    CREATE_TABLE_LIKE_COMMENTS = 1 << 5
    CREATE_TABLE_LIKE_ALL = 0x7FFFFFFF

class TransactionStmtKind(IntEnum):
    TRANS_STMT_BEGIN = 0
    TRANS_STMT_START = 1
    TRANS_STMT_COMMIT = 2
    TRANS_STMT_ROLLBACK = 3
    TRANS_STMT_SAVEPOINT = 4
    TRANS_STMT_RELEASE = 5
    TRANS_STMT_ROLLBACK_TO = 6
    TRANS_STMT_PREPARE = 7
    TRANS_STMT_COMMIT_PREPARED = 8
    TRANS_STMT_ROLLBACK_PREPARED = 9

class VacuumOption(IntEnum):
    VACOPT_VACUUM = 1 << 0
    VACOPT_ANALYZE = 1 << 1
    VACOPT_VERBOSE = 1 << 2
    VACOPT_FREEZE = 1 << 3
    VACOPT_FULL = 1 << 4
    VACOPT_NOWAIT = 1 << 5
    VACOPT_SKIPTOAST = 1 << 6
    VACOPT_DISABLE_PAGE_SKIPPING = 1 << 7

class VariableSetKind(IntEnum):
    VAR_SET_VALUE = 0
    VAR_SET_DEFAULT = 1
    VAR_SET_CURRENT = 2
    VAR_SET_MULTI = 3
    VAR_RESET = 4
    VAR_RESET_ALL = 5

class ViewCheckOption(IntEnum):
    NO_CHECK_OPTION = 0
    LOCAL_CHECK_OPTION = 1
    CASCADED_CHECK_OPTION = 2

class WCOKind(IntEnum):
    WCO_VIEW_CHECK = 0
    WCO_RLS_INSERT_CHECK = 1
    WCO_RLS_UPDATE_CHECK = 2
    WCO_RLS_CONFLICT_CHECK = 3


# #define-ed constants

ACL_INSERT = 1<<0

ACL_SELECT = 1<<1

ACL_UPDATE = 1<<2

ACL_DELETE = 1<<3

ACL_TRUNCATE = 1<<4

ACL_REFERENCES = 1<<5

ACL_TRIGGER = 1<<6

ACL_EXECUTE = 1<<7

ACL_USAGE = 1<<8

ACL_CREATE = 1<<9

ACL_CREATE_TEMP = 1<<10

ACL_CONNECT = 1<<11

N_ACL_RIGHTS = 12

ACL_NO_RIGHTS = 0

FRAMEOPTION_NONDEFAULT = 0x00001

FRAMEOPTION_RANGE = 0x00002

FRAMEOPTION_ROWS = 0x00004

FRAMEOPTION_BETWEEN = 0x00008

FRAMEOPTION_START_UNBOUNDED_PRECEDING = 0x00010

FRAMEOPTION_END_UNBOUNDED_PRECEDING = 0x00020

FRAMEOPTION_START_UNBOUNDED_FOLLOWING = 0x00040

FRAMEOPTION_END_UNBOUNDED_FOLLOWING = 0x00080

FRAMEOPTION_START_CURRENT_ROW = 0x00100

FRAMEOPTION_END_CURRENT_ROW = 0x00200

FRAMEOPTION_START_VALUE_PRECEDING = 0x00400

FRAMEOPTION_END_VALUE_PRECEDING = 0x00800

FRAMEOPTION_START_VALUE_FOLLOWING = 0x01000

FRAMEOPTION_END_VALUE_FOLLOWING = 0x02000

PARTITION_STRATEGY_LIST = 'l'

PARTITION_STRATEGY_RANGE = 'r'

FKCONSTR_ACTION_NOACTION = 'a'

FKCONSTR_ACTION_RESTRICT = 'r'

FKCONSTR_ACTION_CASCADE = 'c'

FKCONSTR_ACTION_SETNULL = 'n'

FKCONSTR_ACTION_SETDEFAULT = 'd'

FKCONSTR_MATCH_FULL = 'f'

FKCONSTR_MATCH_PARTIAL = 'p'

FKCONSTR_MATCH_SIMPLE = 's'

OPCLASS_ITEM_OPERATOR = 1

OPCLASS_ITEM_FUNCTION = 2

OPCLASS_ITEM_STORAGETYPE = 3

CURSOR_OPT_BINARY = 0x0001

CURSOR_OPT_SCROLL = 0x0002

CURSOR_OPT_NO_SCROLL = 0x0004

CURSOR_OPT_INSENSITIVE = 0x0008

CURSOR_OPT_HOLD = 0x0010

CURSOR_OPT_FAST_PLAN = 0x0020

CURSOR_OPT_GENERIC_PLAN = 0x0040

CURSOR_OPT_CUSTOM_PLAN = 0x0080

CURSOR_OPT_PARALLEL_OK = 0x0100

REINDEXOPT_VERBOSE = 1 << 0
